version: '2'
services:
  challenge:
    container_name: ppflw
    build: .
    ports:
      - "8080:8080"
    networks:
      - application-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - application-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    networks:
      - application-network

networks:
  application-network:
    driver: bridge