version: '3'
services:
  consumer:
    container_name: consumer
    build: ppflw_consumer
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - application-network

  producer:
    build: ppflw_producer
    ports:
      - "8080:8080"
    networks:
      - application-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - application-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    networks:
      - application-network

  postgres:
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - application-network

networks:
  application-network:
    driver: bridge